<div style="float: right;margin-right: 100px;padding-top:10px;position: relative">

    <div style="text-align: center; margin-bottom: 10px">
        <a href="https://www.maxigame.com/odeme-secenekleri.html" title="Maxigame Ödeme Seçenekleri" target="_blank">
            <img src="/assets/img/maxigame_satis.gif">
        </a>
    </div>


    <h4 style="text-align: center;color: #c2843b;font-size: 25px;border-bottom: 2px solid;">
        Sponsorlar
    </h4>
    <div style="text-align: center; margin-bottom: 10px">
        <a href="http://www.maxigame.org" title="Maxigame" target="_blank">
            <img src="https://www.maxigame.com/img/logo.png" style="width: 160px; height: auto;">
        </a>
    </div>
    <div style="text-align: center; margin-bottom: 10px">
        <a href="http://www.joymax.org" title="Joymax.org" target="_blank">
            <img src="/assets/img/joymax.png" style="width: 160px; height: auto;">
        </a>
    </div>
    <div style="text-align: center; margin-bottom: 20px">
        <a href="https://www.extraloob.com/forums/" title="ExtraLoob" target="_blank">
            <img src="https://www.extraloob.com/logo/exlmavioptimize.png" style="width: 150px; height: auto;">
        </a>
    </div>


</div>

</div>


<div id="footer">
    <div id="fleft">
        İçerik <a style="font-weight:bold;" target="_blank" href="https://bubblysilkroad.com">BubblyGame</a>'e Aittir İzinsiz
        Kopyalanması ve Kullanılması Yasaktır. <br>&copy; BubblyGame 2018<br>

        <a href="/">Anasayfa</a> |
        <a href="/galeri">Galeri</a> |
        <a href="/market">Market</a> |
        <a href="/rank/AlchemyRank">Rank</a> |
        <a href="/download">Download</a> |
        <a href="/destek">Yardım</a> |


    </div>
    <div id="fright">
        <img src="<?=Settings::getConfig('OyunLogo1')?>" height="70px"/>
        <img src="/assets/img/bubbly.png" height="70px"/>
    </div>
</div>
</body>
<script src="/assets/js/bootstrap.min.js"></script>
</html>