<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>403 Not Found</title>
    <style> Body {
            background-color: #1d3a58;
        }
    </style>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-68588354-4"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-68588354-4');

    </script>
</head>
<body>
    <div id="NotFound" align="center" style="color: white;">
        <?=$message?><br>
        <img src="/aasets/img/404Error.png"/>
    </div>
</body>
</html>
