<?php include "layouts/header.phtml"; ?>
<script src='https://www.google.com/recaptcha/api.js'></script>
<div class="ConLeft">
    <h1>
        Şifre Değiştir
        <span style="float:right;">
            <a href="/profilim">
                <img src="/assets/tema1/img/ui/Back_icon.png" width="24" height="24" title="Geri Dön" alt="Geri Dön"/>
            </a>
        </span>
    </h1>
    <div id="Pageislem">
        <span id="beginislembg"></span>
        <div class="islemicerik">
            <? if (getMessage('error')) { ?>
                <div class="msg errorMsg">
                    <?= getMessage('error', true) ?>
                </div>
            <? } ?>
            <form class="SifremiDegistir" action="" method="post">
                <span>
                    <label class="label1">Gizli Yanıt</label>
                    <input class="inputstil" type="text" required name="GizliYanit" minlength=4 maxlength=16
                           value=""/>
                </span>
                <span>
                    <label class="label1">Mevcut Şifre :</label>
                    <input class="inputstil" type="password" required name="Password" minlength=4 maxlength=16/>
                </span>
                <span>
                    <label class="label1">Yeni Şifre :</label>
                    <input class="inputstil" type="password" required name="Password1" minlength=4 maxlength=16/>
                </span>
                <span>
                    <label class="label1">Yeni Şifre Tekrar :</label>
                    <input class="inputstil" type="password" required name="Password2" minlength=4 maxlength=16/>
                </span>
                <span>
                    <div style="margin-left: 210px;" class="g-recaptcha"
                         data-sitekey="6LeCbVwUAAAAAPNdbSdajFGsNBbAWO75xAuwfOz8"></div>
                </span>
                <em style=" padding-left:200px;">
                    <input class="sendstil" type="submit" value="GÜNCELLE"/>
                </em>
            </form>
        </div>
        <span id="endislembg"></span>
    </div>
</div>
<?php include "layouts/footer.phtml"; ?>
