<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 3.03.2019
 * Time: 03:32
 */
?>
<!---BLOCK 4-->
<div class="well">
    <h4 class="text-center text-uppercase well-title">SOSYAL MEDYA</h4>
    <div class="fb-page" data-href="https://www.facebook.com/eicsilkroad" data-tabs="timeline,messages"
         data-width="262" data-height="400" data-small-header="true" data-adapt-container-width="true"
         data-hide-cover="false" data-show-facepile="true">
        <blockquote cite="https://www.facebook.com/eicsilkroad" class="fb-xfbml-parse-ignore"><a
                href="https://www.facebook.com/eicsilkroad">Eic Game Facebook</a></blockquote>
    </div>
</div>
<!---BLOCK 4-->
