<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 2.03.2019
 * Time: 17:49
 */
?>
<footer class="container">
    <div class="row">
        <div class="col-lg-5">
            <p class="small">Copyright &copy; <?= Settings::getConfig('OyunAd') ?> <?= date("Y"); ?> </p>
            <p class="small" style="font-size:10px;">Coded by <a href="https://gia-tech.net">gia-tech.net <span class="text-danger" style="font-size:14px;">&hearts;</span></a></small>
            </p>
        </div>
        <div class="col-lg-7">
            <div class="pull-right backlink">
                <p class="small"><a href="/">Anasayfa</a></p>
                <p class="small"><a href="/kayit">Kayıt Ol</a></p>
                <p class="small"><a href="/giris-yap">Giriş Yap</a></p>
                <p class="small"><a href="/destek">Destek</a></p>
                <p class="small"><a href="/ozellikler">Tanıtım</a></p>
                <p class="small"><a href="https://play-eic.com/sozlesme.html">Üyelik Sözleşmesi</a></p>
                <p class="small"><a href="https://fb.com/eicsilkroad" target="_blank">İletişim</a></p>
            </div>
        </div>
    </div>
</footer>

