<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 20.02.2019
 * Time: 21:17
 */
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Alexander Frank">

    <title><?= strlen(getTitle()) ? getTitle() . ' - ' : '' ?> <?= Settings::getConfig('OyunAd') ?></title>

    <link href="/assets/<?= getTheme() ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/<?= getTheme() ?>/css/modern-business.css" rel="stylesheet">
    <link href="/assets/<?= getTheme() ?>/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <link href="/assets/<?= getTheme() ?>/css/silkroad.css" rel="stylesheet" type="text/css">

    <script src="/assets/<?= getTheme() ?>/js/jquery.js"></script>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script async defer
            src="https://connect.facebook.net/tr_TR/sdk.js#xfbml=1&version=v3.2&appId=368793663709143&autoLogAppEvents=1"></script>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-68588354-5"></script>
</head>
<body>
<div id="fb-root"></div>

<?
renderPartial('layouts/menu');
renderPartial('layouts/slider');
?>

<div class="container">
    <div class="row">
        <img style="height: 35px;" src="/assets/<?= getTheme() ?>/img/buffer.png" class="img-responsive center-block"/>
        <hr/>
        <div class="col-md-3">
            <?renderPartial('layouts/userpanel')?>
            <?renderPartial('layouts/server')?>
            <?renderPartial('layouts/sponsor')?>
        </div>
        <div class="col-md-6">
            <?= $content ?>
        </div>
        <div class="col-md-3">
            <?renderPartial('layouts/unique')?>
            <?renderPartial('layouts/discord')?>
            <?renderPartial('layouts/facebook')?>
        </div>
    </div>

    <hr/>
</div>
<?renderPartial('layouts/footer');?>

<script src="/assets/<?= getTheme() ?>/js/bootstrap.min.js"></script>
<script src="/assets/<?= getTheme() ?>/js/silkroad.js"></script>
<script src="/assets/<?= getTheme() ?>/js/map.js"></script>
<script src="/assets/js/ga.js"></script>
<script type="text/javascript">
    $('.carousel').carousel({
        interval: 5000,
        pause: false
    });
    var ServerTime = new Date();
</script>

