<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 2.03.2019
 * Time: 17:48
 */
?>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="/assets/img/logo.png"></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/"><i class="fa fa-home"></i> ANASAYFA</a>
                </li>
                <? if (check_login()) { ?>
                    <li>
                        <a href='/profilim'><i class="fa fa-user"></i> HESABIM</a>
                    </li>
                <? } else { ?>
                    <li class="a-register">
                        <a href='/kayit'><i class="fa fa-lock"></i> KAYIT OL</a>
                    </li>
                    <li class="a-login">
                        <a href='/giris-yap'><i class="fa fa-key"></i> GİRİŞ YAP</a>
                    </li>
                <? } ?>

                <li>
                    <a href="/download"><i class="fa fa-download"></i> İNDİR</a>
                </li>
                <li>
                    <a href="/ranking"><i class="fa fa-area-chart"></i> RANK</a>
                </li>
                <li>
                    <a href="/destek"><i class="fa fa-ticket"></i> DESTEK</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-info-circle"></i> SERVER INFO <b
                            class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/ozellikler">Özellikler</a>
                        </li>
                        <li>
                            <a href="/kurallar">Kurallar</a>
                        </li>
                        <li>
                            <a href="/sss">SSS</a>
                        </li>
                        <li>
                            <a href="https://play-eic.com/sozlesme.html">Sözleşme</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
