<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 20.02.2019
 * Time: 21:17
 */
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Alexander Frank">

    <title><?= strlen(getTitle()) ? getTitle() . ' - ' : '' ?> <?= Settings::getConfig('OyunAd') ?></title>

    <link href="/assets/<?= getTheme() ?>/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/<?= getTheme() ?>/css/modern-business.css" rel="stylesheet">
    <link href="/assets/<?= getTheme() ?>/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <link href="/assets/<?= getTheme() ?>/css/silkroad.css" rel="stylesheet" type="text/css">

    <script src="/assets/<?= getTheme() ?>/js/jquery.js"></script>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script async defer
            src="https://connect.facebook.net/tr_TR/sdk.js#xfbml=1&version=v3.2&appId=368793663709143&autoLogAppEvents=1"></script>
</head>
<body>
<div id="fb-root"></div>

<?
renderPartial('layouts/menu');
renderPartial('layouts/slider');
?>

<div class="container">
    <div class="row">
        <img style="height: 35px;" src="/assets/<?= getTheme() ?>/img/buffer.png" class="img-responsive center-block"/>
        <hr/>
        <div class="col-md-3">
            <!---BLOCK 1-->
            <div class="well">
                <?php if (!user()) { ?>
                    <h4 class="text-center text-uppercase well-title">Giriş Yap</h4>
                    <div class="well-content">
                        <form method='post' autocomplete="off" action="/giris-yap">
                            <div class="form-group">
                                <div class="input-group input-group-sm col-xs-12">
                                    <input type="text" minlength=4 maxlength=16 required class="form-control"
                                           placeholder="Kullanıcı Adı" name="username" autocomplete="off"
                                           style="margin-bottom: 10px;"/>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group input-group-sm col-xs-12">
                                    <input type="password" minlength=4 maxlength=16 required class="form-control"
                                           placeholder="Şifre" name="password" autocomplete="off"
                                           style="margin-bottom: 10px;"/>
                                </div>
                            </div>

                            <input class="btn btn-success btn-sm col-xs-12" type="submit" name="button"
                                   value="Giriş Yap"/>
                        </form>
                        <div class="row">

                            <div class="col-lg-6">
                                <a href="/kayit">
                                    <small>KAYIT OL</small>
                                </a>
                            </div>
                            <div class="col-lg-6">
                                <a href="/sifre-unuttum">
                                    <small>ŞİFRE SIFIRLA</small>
                                </a>
                            </div>
                        </div>
                    </div>
                <? } else { ?>
                    <h4 class="text-center text-uppercase well-title">Hesabım</h4>
                    <div class="text-center">
                        Hoşgeldin, <?= user()->StrUserID ?>.
                    </div>
                    <div class="well-content">
                        <div class="btn-group-vertical" role="group" style="width: 100%;" aria-label="...">
                            <a class="btn btn-primary" type="button" href="/profilim"><i class="fa fa-user"></i>
                                Hesabım</a>
                            <a class="btn btn-primary" type="button" href="/destek"><i class="fa fa-ticket"></i>
                                Destek Talebi</a>
                            <a class="btn btn-primary" type="button" href="/epin-yukle"><i class="fa fa-money"></i>
                                Bakiye [<?= user()->BakiyeTL ?>]</a>
                            <a class="btn btn-primary" type="button" href="/market"><i class="fa fa-shopping-cart"></i>
                                Market</a>
                            <a class="btn btn-primary" type="button" href="/profilim/ayarlar"><i
                                        class="fa fa-cogs"></i> Ayarlar</a>
                            <!--                            <a class="btn btn-warning" type="button" href="/vote"><i class="fa fa-bullhorn"></i>Vote</a>-->
                            <a class="btn btn-primary" type="button" href="/cikis"><i class="fa fa-sign-out"></i>
                                Çıkış Yap</a>
                        </div>
                    </div>
                <? } ?>
            </div>
            <!---BLOCK 1-->

            <!---BLOCK 2-->
            <div class="well">
                <h4 class="text-center text-uppercase well-title">Sunucu Bilgileri</h4>
                <div class="well-content">
                    <?php
                    $onlineUser = Settings::getToplamOnlineOyuncu();
                    $capacity = Settings::getConfig('Capacity');
                    $bosAlan = $capacity - $onlineUser;
                    $xx = $onlineUser * 100 / $capacity;
                    $class = $xx > 90 ? "progress-bar-danger" : ($xx > 70 ? "progress-bar-warning" : "progress-bar-success");
                    ?>
                    <div class="progress">
                        <div class="progress-bar <?=$class?>" style="width: <?=$onlineUser * 100 / $capacity?>%">
                            <?if($bosAlan * 100 / $capacity < 75){ echo "$onlineUser / $capacity"; }?>
                        </div>
                        <div class="progress-bar progress-bar-default" style="width: <?=$bosAlan * 100 / $capacity?>%">
                            <?if($bosAlan * 100 / $capacity >= 75){ echo "$onlineUser / $capacity"; }?>
                        </div>
                    </div>
                    <p class="small"><i class="fa fa-fw fa-clock-o"></i> Time:<span class="text-info pull-right" id="tServerTime"></span></p>
                    <p class="small"><i class="fa fa-fw fa-desktop"></i> Online:<span
                                class="text-info pull-right"><?= $onlineUser ?>
                            / <?= $capacity ?></span></p>
                    <p class="small"><i class="fa fa-fw fa-check"></i> Cap:<span
                                class="text-info pull-right"><?= Settings::getSwProperty('cap'); ?></span></p>
                    <p class="small"><i class="fa fa-fw fa-check"></i> Mastery Cap:<span
                                class="text-info pull-right"><?= Settings::getSwProperty('mastery_cap'); ?></span></p>
                    <p class="small"><i class="fa fa-fw fa-users"></i> Irk<span
                                class="text-info pull-right">EU & CH</span></p>
                    <p class="small"><i class="fa fa-fw fa-flask"></i> EXP & SP<span
                                class="text-info pull-right"><?= Settings::getSwProperty('exp'); ?></span></p>
                    <p class="small"><i class="fa fa-fw fa-users"></i> Party<span
                                class="text-info pull-right"><?= Settings::getSwProperty('ptexp'); ?></span></p>
                    <p class="small"><i class="fa fa-fw fa-money"></i> Gold & Drop<span
                                class="text-info pull-right"><?= Settings::getSwProperty('drop'); ?></span></p>
                    <p class="small"><i class="fa fa-fw fa-star"></i> Tradegoods<span
                                class="text-info pull-right"><?= Settings::getSwProperty('tradegoods'); ?></span></p>
                    <p class="small"><i class="fa fa-fw fa-star"></i> Alchemy<span
                                class="text-info pull-right"><?= Settings::getSwProperty('alchemy'); ?></span></p>
                    <p class="small"><i class="fa fa-fw fa-exclamation"></i> IP Limit<span
                                class="text-warning pull-right"><?= Settings::getSwProperty('iplimit'); ?></span></p>
                    <p class="small"><i class="fa fa-fw fa-exclamation"></i> PC Limit<span
                                class="text-warning pull-right"><?= Settings::getSwProperty('pclimit'); ?></span></p>
                    <p class="small"><i class="fa fa-fw fa-exclamation"></i> JOB Limit<span
                                class="text-warning pull-right"><?= Settings::getSwProperty('joblimit'); ?></span></p>
                    <hr/>
                    <? $hotanFW = Settings::getFortress(3); ?>
                    <p class="text-justify small">
                        <img style='vertical-align:middle;'
                             src='/assets/<?= getTheme() ?>/img/fortress/fort-hotan.png'/>
                        Hotan <i class="text-info"> <?= $hotanFW['TaxRatio'] ? $hotanFW['TaxRatio'] : "0" ?>%</i> Tax
                        <span class="text-info pull-right">
                        <?php echo $hotanFW['Name'] == 'Dummy' || !strlen($hotanFW['Name']) ? '< Hiç kimse >' : $hotanFW['Name'] ?>
                    </span>
                    </p>
                    <hr/>
                    <? $job = Settings::getJob(); ?>
                    <div class="progress">
                        <div class="progress-bar progress-bar-success" style="width: <?= $job[1]['size']; ?>%">
                            Trader <?= $job[1]['size']; ?>%
                            <span class="sr-only">Trader</span>
                        </div>
                        <div class="progress-bar progress-bar-info" style="width: <?= $job[3]['size']; ?>%">
                            Hunter <?= $job[3]['size']; ?>%
                            <span class="sr-only">Hunter</span>
                        </div>
                        <div class="progress-bar progress-bar-danger" style="width: <?= $job[2]['size']; ?>%">
                            Thief <?= $job[2]['size']; ?>%
                            <span class="sr-only">Thief</span>
                        </div>
                    </div>
                </div>
            </div>
            <!---BLOCK 2-->

        </div>
        <div class="col-md-9">
            <?= $content ?>
        </div>
    </div>

    <hr/>
</div>

<?renderPartial('layouts/footer');?>

<script src="/assets/<?= getTheme() ?>/js/bootstrap.min.js"></script>
<script src="/assets/<?= getTheme() ?>/js/silkroad.js"></script>
<script src="/assets/<?= getTheme() ?>/js/map.js"></script>
<script type="text/javascript">
    $('.carousel').carousel({
        interval: 5000,
        pause: false
    });
    var ServerTime = new Date();
</script>
<?php
if ($_GET["page"] === "vote") {
    ?>
    <script src="/assets/<?= getTheme() ?>/js/voteScript.js"></script>
    <script type="text/javascript">
        var oldHist = history.length;

        function validate() {
            interval = setInterval(function () {
                if (oldHist != history.length) {
                    window.opener.document.getElementById("response").innerHTML = '<strong><a href="/vote/" class="text-danger">Refresh</a></strong>';
                    oldHist = history.length;
                    clearInterval(interval);
                    window.opener.validate();
                } else {
                    if (window.opener === null) {
                        clearInterval(interval);
                    } else {
                        window.opener.document.getElementById("response").innerHTML = "Still not voted...";
                    }
                }
            }, 1000);
        }
    </script>
    <?php
}
?>
