<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 20.02.2019
 * Time: 21:37
 */
?>

<header id="sliderVinbardia" class="carousel slide hidden-sm hidden-xs">
    <ol class="carousel-indicators">
        <?foreach (Settings::getSliders() as $i=>$news) { ?>
        <li data-target="#sliderVinbardia" data-slide-to="<?=$i?>" class="<?=$i == 0 ? 'active' : ''?>"></li>
        <?}?>
    </ol>
    <div class="carousel-inner">
        <?foreach (Settings::getSliders() as $item) { ?>
            <div class="item active">
                <div class="fill bg-slider-4" style="background-image:url('<?= $item['ResimUrl'] ?>')"></div>
                <div class="carousel-caption">
                    <h2><?= $item['Title'] ?></h2>
                </div>
            </div>
        <?}?>
    </div>
    <a class="left carousel-control" href="#sliderVinbardia" data-slide="prev">
        <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#sliderVinbardia" data-slide="next">
        <span class="icon-next"></span>
    </a>
</header>


