<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 28.02.2019
 * Time: 00:16
 */
?>

<div class="panel panel-default register-white">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-money"></i> TL / E-PIN Yükle</h3>
    </div>
    <div class="panel-body">
        <ul class="balance">
            <?if(Settings::getConfig('Maxigame_aktif')){?>
                <li>
                    <a href="/epin-yukle/maxigame"><img src="/assets/img/maxicard.png"> </a>
                </li>
            <?}?>
            <?if(Settings::getConfig('Paywant_aktif')){?>
                <li>
                    <a href="/epin-yukle/paywant"><img src="/assets/img/paywant_ile_ode_whmcs.png"></a>
                </li>
            <?}?>
            <li>
                <a href="/epin-yukle/epin"><img src="/assets/img/epin.jpg"></a>
            </li>
        </ul>

    </div>
</div>
