<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 25.02.2019
 * Time: 22:01
 */
?>

<div class="panel-group text-white" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Neden Kayıt kapalıdır?</a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse">
            <div class="panel-body">
                Beta ve büyük açılış öncesi kayıtlar kapatılır. Bu veri kaybını önlemek içindir.
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">+18 Uyarısı neden alıyorum?</a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse">
            <div class="panel-body">
                Bunun sebebi bilgisayarınızda PC Limit için gerekli bilgileri alamadığımızdan kaynaklanıyor. Oyun klasöründe EicFilter.dll olduğundan emin olunuz. Var ise bilgisayarınızı işletim sistemini ve bit versiyonunu facebook üzerinden bize iletiniz.
            </div>
        </div>
    </div>
</div>
