<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 20.02.2019
 * Time: 21:27
 */

?>
<?foreach (Settings::getNews() as $news) { ?>
    <div class="row featurette">
        <div class="col-md-3">
            <a class="thumbnail hidden-sm hidden-xs">
                <img alt="<?= $news['Baslik'] ?>" class="img-responsive center-block maxDefaultThumb" src="<?= $news['Resim'] ?>">
            </a>
        </div>
        <div class="col-md-9">
            <h2 class="featurette-heading" style="margin-top:0;"><?= $news['Baslik'] ?></h2>
            <p class="informationText"><?= $news['Tanim'] ?></p>
            <p class="informationText"><?= $news['Metin'] ?></p>
            <span class="pull-right"> <small class="btn btn-primary btn-xs"><?= $news['Tarih'] ?></small>  </span>
            <span class="pull-right"> <small class="btn btn-info btn-xs">Duyuru </small> </span>
        </div>
    </div>
    <hr>
<? } ?>