<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 28.02.2019
 * Time: 00:35
 */

?>
<div class="panel panel-default register-white">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-money"></i> E-Pin ile TL Yükle</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-12">
                <?php
                if(getMessage('error')){
                    ?>
                    <br/>
                    <div class="input-group input-group-sm col-xs-12">
                        <div class="alert alert-danger" role="alert"><?= getMessage('error',true); ?></div>
                    </div>
                    <?php
                }?>
                <form method="post" class="form-horizontal">

                    <div class="form-group">
                        <label class="label col-sm-12">E-Pin Kart Kodu</label>
                        <div class="col-sm-12">
                            <input class="form-control" type="text" required name="CardCode" placeholder="E-Pin Kart Kodu"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="label col-sm-12">E-Pin Kart Şifresi</label>
                        <div class="col-sm-12">
                            <input class="form-control" type="text" required name="Password" placeholder="E-Pin Kart Şifresi"/>
                        </div>
                    </div>
                    <br>
                    <button class="btn btn-success col-xs-12" type="submit" value="Yükle">Yükle</button>
                </form>
            </div>
        </div>
    </div>
</div>