<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 10.03.2019
 * Time: 02:46
 */

?>
<div class="panel panel-default register-white">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-history"></i> Pet Aktar</h3>
    </div>
    <div class="panel-body">
        <?php
        if(getMessage('error')){
            ?>
            <br/>
            <div class="input-group input-group-sm col-xs-12">
                <div class="alert alert-danger" role="alert"><?= getMessage('error',true); ?></div>
            </div>
            <?php
        }
        if(getMessage('success')){
            ?>
            <br/>
            <div class="input-group input-group-sm col-xs-12">
                <div class="alert alert-success" role="alert"><?= getMessage('success',true); ?></div>
            </div>
            <?php
        }
        ?>
        <form method="post">
            <div class="form-group">
                <label class="control-label">Karakter Seçiniz</label>
                <select name="CharName" class="form-control input-sm">
                    <?foreach ($charList as $getChar) {?>
                        <option><?=$getChar['CharName16']?></option>
                    <?}?>
                </select>
                <div class="alert alert-danger">
                    Lütfen karakteriniz oyunda olmasın!
                </div>
            </div>
            <button type="submit" class="btn btn-success">Gönder</button>
        </form>

    </div>
</div>