<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 2.03.2019
 * Time: 02:05
 */
?>
<div class="panel panel-default register-white">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-key"></i> ŞİFRE SIFIRLA</h3>
    </div>
    <div class="panel-body">
        <?php
        if(getMessage('error')){
            ?>
            <br/>
            <div class="input-group input-group-sm col-xs-12">
                <div class="alert alert-danger" role="alert"><?= getMessage('error',true); ?></div>
            </div>
            <?php
        }
        if(getMessage('success')){
            ?>
            <br/>
            <div class="input-group input-group-sm col-xs-12">
                <div class="alert alert-success" role="alert"><?= getMessage('success',true); ?></div>
            </div>
            <?php
        }
        ?>
        <form method="POST">
            <div class="form-group">
                <div class="row">
<!--                    <div class="input-group-sm col-sm-6">-->
<!--                        <label for="username">Kullanıcı Adı</label>-->
<!--                        <div class="input-group input-group-sm">-->
<!--                            <input type="text" minlength=4 maxlength=16 required class="form-control" placeholder="Kullanıcı Adı" name="UserName" value="--><?//= isset($_POST['UserName']) ? $_POST['UserName'] : '' ?><!--" autocomplete="off" />-->
<!--                            <span class="input-group-addon hidden-sm hidden-xs">Uzunluk 4 - 16</span>-->
<!--                        </div>-->
<!--                    </div>-->
                </div>
            </div>

        </form>
    </div>
</div>
