<?php
/**
 * Created by PhpStorm.
 * User: Alexander
 * Date: 24.06.2015
 * Time: 12:02
 */
?>
<ul class="list-group text-info font13">
<!--    <li class="list-group-item">1. &rightarrow; Racist words in [allchat] and [global} are not allowed.<small class="pull-right text-warning">(Kick)</small></li>-->
<!--    <li class="list-group-item">2. &rightarrow; Advertising other servers on [globals] are forbidden.<small class="pull-right text-danger">(Permanent ban)</small></li>-->
<!--    <li class="list-group-item">3. &rightarrow; Using bugs, exploits & hacks.<small class="pull-right text-danger">(Permanent ban)</small></li>-->
<!--    <li class="list-group-item">4. &rightarrow; Selling-, trading-, buying- Accounts,Items or Gold for real money<small class="pull-right text-danger">(Permanent ban)</small></li>-->
<!--    <li class="list-group-item">5. &rightarrow; Spreading false information about our team such as corruption and no fair play.<small class="pull-right text-danger">(Permanent ban)</small></li>-->
<!--    <li class="list-group-item">6. &rightarrow; [allchat] spam in any town.<small class="pull-right text-warning">(Kick)</small></li>-->
<!--    <li class="list-group-item">7. &rightarrow; Charing back and acquiring items on an illegal way, suspicious items may be deleted without notice or warning.</li>-->
<!--    <li class="list-group-item">8. &rightarrow; Being involved in hacking or scamming or anything in that direction.<small class="pull-right text-danger">(Permanent ban)</small></li>-->
<!--    <li class="list-group-item">9. &rightarrow; Impersonating other players through faking their names.<small class="pull-right text-danger">(Permanent ban)</small></li>-->
<!--    <li class="list-group-item">10. &rightarrow; Job abusing in all ways. (Safezone, Friends, Dropping etc.)<small class="pull-right text-danger">(Permanent ban)</small></li>-->
<!--    <li class="list-group-item">11. &rightarrow; Insulting Developer, Gamemaster and Staff. <small class="pull-right text-warning">(Kick)</small></li>-->
</ul>
