
<div class="panel panel-default register-white">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-credit-card"></i> Web Market Satın Al</h3>
    </div>
    <div class="panel-body">
        <?php
        if(getMessage('error')){
            ?>
            <br/>
            <div class="input-group input-group-sm col-xs-12">
                <div class="alert alert-danger" role="alert"><?= getMessage('error',true); ?></div>
            </div>
            <?php
        }
        if(getMessage('success')){
            ?>
            <br/>
            <div class="input-group input-group-sm col-xs-12">
                <div class="alert alert-success" role="alert"><?= getMessage('success',true); ?></div>
            </div>
            <?php
        }
        ?>
        <b>Bakiyeniz :</b> <?php echo number_format(user()->BakiyeTL,2) ?> ₺<br>
        <b>Satın alınmak istenen ürün:</b> <?=$mall->ItemName?> <br>
        <b>Fiyatı:</b> <?=number_format($mall->ItemName,2)?> ₺ <br>
<br><br>
        <form method="post">
            <div class="form-group">
                <label class="control-label">Karakter Seçiniz</label>
                <select name="char" class="form-control input-sm">
                    <?foreach (User::getChars(user()->JID) as $getChar) {?>
                        <option><?=$getChar['CharName16']?></option>
                    <?}?>
                </select>
                <div class="alert alert-danger">
                    Lütfen karakteriniz oyunda olmasın!
                </div>
            </div>
            <button type="submit" class="btn btn-success">Gönder</button>
        </form>

    </div>
</div>



<div class="ConLeft" id="Market">
    <h1>Web Market Item Mall
        <span style="float:right;">
            <a href="/profilim">
                <img src="/assets/tema1/img/ui/Back_icon.png" width="24" height="24" title="Geri Dön" alt="Geri Dön"/>
            </a>
        </span>
        <small>Bakiyeniz : <?php echo user()->BakiyeTL ?> TL</small>
    </h1>
    <div class="Seperator"></div>
    <br>
    <form method="post">
        Lütfen Char Seçiniz:<br>
        <select name="char">
            <?foreach (User::getChars(user()->JID) as $getChar) {?>
                <option><?=$getChar['CharName16']?></option>
            <?}?>
        </select>
        <button>Gönder</button>
    </form>

</div>
