<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 20.02.2019
 * Time: 23:58
 */
?>
<div class="panel panel-default register-white">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-ticket"></i> Desek Talebi Oluştur</h3>
    </div>
    <div class="panel-body">
        <?php
        if(getMessage('error')){
            ?>
            <br/>
            <div class="input-group input-group-sm col-xs-12">
                <div class="alert alert-danger" role="alert"><?= getMessage('error',true); ?></div>
            </div>
            <?php
        }
        if(getMessage('success')){
            ?>
            <br/>
            <div class="input-group input-group-sm col-xs-12">
                <div class="alert alert-success" role="alert"><?= getMessage('success',true); ?></div>
            </div>
            <?php
        }
        ?>
        <form method="POST">
            <div class="form-group">
                <div class="row">
                    <div class="input-group-sm col-sm-6">
                        <label for="CharName16">Karakter</label>
                        <select class="form-control" name="CharName16" id="CharName16">
                            <?foreach ($chars as $char) {?>
                                <option><?=$char['CharName16']?></option>
                            <?}?>
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="input-group-sm col-sm-12">
                        <label for="Message">Message</label>
                        <textarea required class="form-control" style="height: 150px;" minlength="25" maxlength="300"  placeholder="Mesajınız" name="Message"></textarea>
                    </div>

                </div>
            </div>

            <div class="controls form-inline margin-top10">
                <input class="btn btn-success btn-md col-xs-4 pull-right" type="submit" name="button"  value="Oluştur" />
                <div class="clearfix"></div>
            </div>
        </form>
    </div>
</div>

