<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 10.02.2019
 * Time: 21:50
 */

?>

<div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Yeni Dosya</span>
        <h3 class="page-title">Dosyalar</h3>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 mb-4">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">Yeni Dosya</h6>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item p-3">
                    <div class="row">
                        <div class="col">
                            <form method="post">
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="Dosya_Host">Dosya_Host</label>
                                        <input type="text" class="form-control" id="Dosya_Host" name="Dosya_Host" placeholder="Dosya_Host" value="<?=isset($settings->Dosya_Host) ? $settings->Dosya_Host : ''?>">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="Dosya_Type">Dosya_Type</label>
                                        <input type="text" class="form-control" id="Dosya_Type" name="Dosya_Type" placeholder="Dosya_Type" value="<?=isset($settings->Dosya_Type) ? $settings->Dosya_Type : ''?>">
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="Dosya_Url">Dosya_Url</label>
                                        <input type="text" class="form-control" id="Dosya_Url" name="Dosya_Url" placeholder="Dosya_Url" value="<?=isset($settings->Dosya_Url) ? $settings->Dosya_Url : ''?>">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="Dosya_Boyut">Dosya_Boyut</label>
                                        <input type="text" class="form-control" id="Dosya_Boyut" name="Dosya_Boyut" placeholder="Dosya_Boyut" value="<?=isset($settings->Dosya_Boyut) ? $settings->Dosya_Boyut : ''?>">
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Kaydet</button>
                            </form>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>