<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 9.02.2019
 * Time: 21:54
 */?>

<div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Overview</span>
        <h3 class="page-title">Dosyalar</h3>
    </div>
</div>

<div class="row">
    <div class="col">
        <div class="card card-small mb-4">
            <div class="card-header border-bottom">
                <div class="row">
                    <h6 class="m-0 col-6">Dosyalar</h6>
                    <div class="col-6 text-right">
                        <a href="/panel/downloads/add" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> Yeni</a>
                    </div>
                </div>
            </div>
            <div class="card-body p-0 pb-3 text-center">
                <table class="table mb-0">
                    <thead class="bg-light">
                    <tr>
                        <th scope="col" class="border-0">#</th>
                        <th scope="col" class="border-0">Dosya_Host</th>
                        <th scope="col" class="border-0">Dosya_Url</th>
                        <th scope="col" class="border-0">Dosya_Boyut</th>
                        <th scope="col" class="border-0">Dosya_Type</th>
                        <th scope="col" class="border-0">Dosya_Tarih</th>
                        <th scope="col" class="border-0"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    if(isset($downloads) && count($downloads) > 0){
                        foreach ($downloads as $download) {?>
                            <tr>
                                <td><?=$download->ID?></td>
                                <td><?=$download->Dosya_Host?></td>
                                <td><?=$download->Dosya_Url?></td>
                                <td><?=$download->Dosya_Boyut?></td>
                                <td><?=$download->Dosya_Type?></td>
                                <td><?=$download->Dosya_Tarih?></td>
                                <td>
                                    <a onclick="return confirm('Emin misiniz?');" class="btn btn-danger btn-xs" href="/panel/downloads/sil/<?=$download->ID?>">Sil</a>
                                </td>
                            </tr>
                        <?}
                    }else{?>
                        <tr>
                            <td colspan="7">Kayıt bulunamadı</td>
                        </tr>
                    <?}?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
