<!doctype html>
<html class="no-js h-100" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Panel Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="//use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0" href="/panel/styles/shards-dashboards.1.1.0.min.css">
    <link rel="stylesheet" href="/panel/styles/extras.1.1.0.min.css">
    <script async defer src="//buttons.github.io/buttons.js"></script>
</head>
<body class="h-100">
<div class="container-fluid">

    <br><br>
    <div class="col-lg-3 col-md-5 auth-form mx-auto my-auto">
        <div class="card">
            <div class="card-body">
                <div class="auth-form__logo d-table mx-auto mb-3"><h2>GiaPanel</h2></div>
                <h5 class="auth-form__title text-center mb-4">Giriş Yap</h5>
                <form method="post">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Kullanıcı Adı</label>
                        <input type="text" required name="username" class="form-control" id="exampleInputEmail1" placeholder="Kullanıcı Adı">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Şifre</label>
                        <input type="password" required name="password" class="form-control" id="exampleInputPassword1" placeholder="Şifre">
                    </div>
                    <button type="submit" class="btn btn-pill btn-accent d-table mx-auto">Access Account</button>
                </form>
            </div>
        </div>
        <div class="auth-form__meta d-flex mt-4">
            <a href="/panel/reset-password">Şifre mi Unuttum</a>
        </div>
    </div>


    <script src="//code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>