<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 10.02.2019
 * Time: 21:50
 */

?>

<div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Yeni Duyuru</span>
        <h3 class="page-title">Slider</h3>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 mb-4">
        <div class="card card-small">
            <div class="card-header border-bottom">
                <h6 class="m-0">Yeni Slider</h6>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item p-3">
                    <div class="row">
                        <div class="col">
                            <form method="post">
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="Title">Title</label>
                                        <input type="text" class="form-control" id="Title" name="Title" placeholder="Title" value="<?=isset($settings->Title) ? $settings->Title : ''?>">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="Description">Description</label>
                                        <input type="text" class="form-control" id="Description" name="Description" placeholder="Description" value="<?=isset($settings->Description) ? $settings->Description : ''?>">
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="ResimUrl">ResimUrl</label>
                                        <input type="text" class="form-control" id="ResimUrl" name="ResimUrl" placeholder="ResimUrl" value="<?=isset($settings->ResimUrl) ? $settings->ResimUrl : ''?>">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="Thumb">Thumb</label>
                                        <input type="text" class="form-control" id="Thumb" name="Thumb" placeholder="Thumb" value="<?=isset($settings->Thumb) ? $settings->Thumb : ''?>">
                                    </div>
                                </div>
                                    <div class="form-group">
                                        <label for="Url">Url</label>
                                        <input type="text" class="form-control" id="Url" name="Url" placeholder="Url" value="<?=isset($settings->Url) ? $settings->Url : ''?>">
                                    </div>

                                <div class="form-group">
                                    <label for="">Durum</label>
                                    <div class="custom-control custom-toggle custom-toggle-sm mb-1">
                                        <input type="checkbox" id="Service" name="Service" class="custom-control-input" <?=$settings->Service == '1' ? 'checked' : ''?>>
                                        <label class="custom-control-label" for="Service"> &nbsp;</label>
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary">Kaydet</button>
                            </form>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>