<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 9.02.2019
 * Time: 21:54
 */?>

<div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
        <span class="text-uppercase page-subtitle">Overview</span>
        <h3 class="page-title">Slider</h3>
    </div>
</div>

<div class="row">
    <div class="col">
        <div class="card card-small mb-4">
            <div class="card-header border-bottom">
                <div class="row">
                    <h6 class="m-0 col-6">Slider</h6>
                    <div class="col-6 text-right">
                        <a href="/panel/sliders/add" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i> Yeni</a>
                    </div>
                </div>
            </div>
            <div class="card-body p-0 pb-3 text-center">
                <table class="table mb-0">
                    <thead class="bg-light">
                    <tr>
                        <th scope="col" class="border-0">#</th>
                        <th scope="col" class="border-0">Title</th>
                        <th scope="col" class="border-0">Description</th>
                        <th scope="col" class="border-0">Url</th>
                        <th scope="col" class="border-0">Service</th>
                        <th scope="col" class="border-0"></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?
                    if(isset($sliders) && count($sliders) > 0){
                        foreach ($sliders as $slider) {?>
                            <tr>
                                <td><?=$slider->ID?></td>
                                <td><?=$slider->Title?></td>
                                <td><?=$slider->Description?></td>
                                <td><?=$slider->Url?></td>
                                <td><?=$slider->Service?></td>
                                <td>
                                    <a onclick="return confirm('Emin misiniz?');" class="btn btn-danger btn-xs" href="/panel/sliders/sil/<?=$slider->ID?>">Sil</a>
                                    <?if($slider->Service){?>
                                    <a onclick="return confirm('Emin misiniz?');" class="btn btn-warning btn-xs" href="/panel/sliders/kapat/<?=$slider->ID?>">Kapat</a>
                                    <?}else{?>
                                        <a onclick="return confirm('Emin misiniz?');" class="btn btn-warning btn-xs" href="/panel/sliders/yayinla/<?=$slider->ID?>">Yayınla</a>
                                    <?}?>
                                </td>
                            </tr>
                        <?}
                    }else{?>
                        <tr>
                            <td colspan="7">Kayıt bulunamadı</td>
                        </tr>
                    <?}?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
