<!-- Main Sidebar -->
<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
    <div class="main-navbar">
        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
            <a class="navbar-brand w-100 mr-0" href="#" style="line-height: 25px;">
                <div class="d-table m-auto">
                    <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 25px;" src="/panel/images/shards-dashboards-logo.svg" alt="GiaPanel">
                    <span class="d-none d-md-inline ml-1">GiaPanel</span>
                </div>
            </a>
            <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
            </a>
        </nav>
    </div>

    <div class="nav-wrapper">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="/panel/">
                    <i class="material-icons">home</i>
                    <span>Anasayfa</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="/panel/users">
                    <i class="material-icons">person</i>
                    <span>Kullanıcılar</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="/panel/chars">
                    <i class="material-icons">person</i>
                    <span>Karakterler</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="/panel/news">
                    <i class="material-icons">table_chart</i>
                    <span>Haberler</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="/panel/sliders">
                    <i class="material-icons">table_chart</i>
                    <span>Slider</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="/panel/settings">
                    <i class="material-icons">table_chart</i>
                    <span>Ayarlar</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="/panel/tickets">
                    <i class="material-icons">edit</i>
                    <span>Ticket</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="/panel/downloads">
                    <i class="material-icons">table_chart</i>
                    <span>Dosyalar</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="/panel/delete_cache_files">
                    <i class="material-icons">table_chart</i>
                    <span>Cache Temizle</span>
                </a>
            </li>
        </ul>
    </div>
</aside>
<!-- End Main Sidebar -->