<!doctype html>
<html class="no-js h-100" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?=getTitle()?></title>
    <meta name="description" content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="//use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0" href="/panel/styles/shards-dashboards.1.1.0.min.css">
    <link rel="stylesheet" href="/panel/styles/extras.1.1.0.min.css">
    <script async defer src="//buttons.github.io/buttons.js"></script>
</head>
<body class="h-100">
<div class="container-fluid">
    <div class="row">

        <?renderPartial('layouts/_menubar')?>

        <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">
            <div class="main-navbar sticky-top bg-white">
                <!-- Main Navbar -->
                <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">

                    <ul class="navbar-nav border-left flex-row" style="right: 0; position: absolute;">

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                <img class="user-avatar rounded-circle mr-2" src="/panel/images/avatars/0.jpg" alt="User Avatar">
                                <span class="d-none d-md-inline-block"><?=user()->username?></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-small">
                                <a class="dropdown-item" href="/panel/account">
                                    <i class="material-icons">&#xE7FD;</i> Profil</a>
                                <a class="dropdown-item text-danger" href="/panel/logout">
                                    <i class="material-icons text-danger">&#xE879;</i> Çıkış </a>
                            </div>
                        </li>
                    </ul>
                    <nav class="nav">
                        <a href="#" class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left" data-toggle="collapse" data-target=".header-navbar" aria-expanded="false" aria-controls="header-navbar">
                            <i class="material-icons">&#xE5D2;</i>
                        </a>
                    </nav>
                </nav>
            </div>

            <!-- / .main-navbar -->
            <div class="main-content-container container-fluid px-4">
                <?renderPartial('layouts/messages')?>

                <?=$content?>
            </div>

            <footer class="main-footer d-flex p-2 px-3 bg-white border-top">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="/panel">Anasayfa</a>
                    </li>
                </ul>
                <span class="copyright ml-auto my-auto mr-2">Copyright © 2018
              <a href="https://gia-tech.net" rel="nofollow">GiaPanel</a>
            </span>
            </footer>
        </main>
    </div>
</div>

<script src="//code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script src="//unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>
<script src="/panel/scripts/extras.1.1.0.min.js"></script>
<script src="/panel/scripts/shards-dashboards.1.1.0.min.js"></script>
<script src="/panel/scripts/app/app-blog-overview.1.1.0.js"></script>
</body>
</html>



