<? if(getMessage("all")){ ?>
    <?php
    if(getMessage("error")){
        $message = getMessage('error',true);
        $icon = "fa fa-times";
        $class = "alert-danger";
    } ?>
    <?php
    if(getMessage("success")){
        $message = getMessage('success',true);
        $icon = "fa fa-check";
        $class = "alert-success";
    } ?>
    <?php
    if(getMessage("info")){
        $message = getMessage('success',true);
        $icon = "fa fa-info";
        $class = "alert-info";
    } ?>
    <div class="clearfix"></div>
    <div class="alert <?=$class?> alert-dismissible fade show mb-0" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span></button> <i class="<?=$icon?> mx-2"></i>
        <?=$message?>
    </div>

<? } ?>
