<?php
/**
 * Created by IntelliJ IDEA.
 * User: ekrmn60600
 * Date: 12.02.2019
 * Time: 23:02
 */
?>

<div class="shadow-box">
    <div style="font-size:16px;color:#987d48;">
        Giriş Yap
    </div>
    <div id="regbox2">
        <div class="rslider">
            <form method="post">
                <div style="width:230px;">
                    <input required placeholder="Kullanıcı Adı" name="username" id="username" value=""
                                style="margin-top:12px;margin-left:7px;"
                                type="text"><br>
                    <input required placeholder="Şifre" name="password" id="password" value="" style="margin-top:3px;"
                                type="password"><br>
                    <input name="change" id="next1" value="GİRİŞ" type="submit"
                           style="height:30px;"/><br>
                </div>
            </form>
            <div style="width:230px;">
                <div class="step-text"><br><br><br>Password changed sucessfully !</div>
            </div>
        </div>
    </div>

    <br><br>

</div>
