<div class="ConLeft">
    <div id="Pageislem">
        <span id="beginislembg"></span>
        <div class="islemicerik">
            <div id="phptag">
            </div>
            <table class="islemtable" border="0" cellspacing="0" cellpadding="0">
                <tr class="begin">
                    <td class="islem">İşlem</td>
                    <td class="tarih">IP</td>
                    <td class="tarih">Tarih</td>
                </tr>
                <?php
                foreach ($histories as $history) {?>
                    <tr class="listislem">
                        <td class="islem"><?=$history["Durum"]?></td>
                        <td class="tarih"><?=$history["IP"]?></td>
                        <td class="tarih"><?=date('H:i d-m-Y',strtotime($history["Time"]))?></td>
                    </tr>
                <?}?>
            </table>
        </div>
        <span id="endislembg"></span>
    </div>
</div>
